### ISSUE TITLE
Argument for @NotNull parameter 'leftContentTitle' of com/github/obiscr/exceleditor/ui/b/e/c.<init> must not be null

### ISSUE THREAD

**Issue by marisveide** [obiscr/ExcelEditor#11]
When comparing the CSV files inside the ZIP file - it offers to compare those, but in reality fails with the following error:
`Argument for @NotNull parameter 'leftContentTitle' of com/github/obiscr/exceleditor/ui/b/e/c.<init> must not be null`

See attached screenshot.
![Screenshot 2024-10-16 at 09 16 52](https://github.com/user-attachments/assets/73ce8020-ef7a-495a-a8bd-346e48263a89)

**Comment by obiscr** [comment]
Thank for report this issue. Let's clarify whether you're using ExcelReader or ExcelEditor?

**Comment by marisveide** [comment]
I am trying with ExcelEditor.
Tried also with ExcelReader - the same error.

**Comment by obiscr** [comment]
It‘s has been fixed, please update to the latest version, thank you!
