### ISSUE TITLE
Not compatible with IntelliJ IDEA Ultimate 2024.3

### ISSUE THREAD

**Issue by ofry** [obiscr/ExcelEditor#12]
Latest version of ExcelEditor (ExcelEditor 2024.11.1-222.242) compatible with IntelliJ IDEA Ultimate version range 2022.2 — 2024.2.4.

**Comment by obiscr** [comment]
Thank you, I will support new version ASAP.

**Comment by obiscr** [comment]
@ofry Hi, the new version has released.
