### ISSUE TITLE
两个Excel对比功能貌似有功能缺陷

### ISSUE THREAD

**Issue by 834116404** [obiscr/ExcelEditor#8]
![image](https://github.com/obiscr/ExcelEditor/assets/36099756/30efec4c-9275-4100-b4ff-bd98514e64c0)

两个Excel对比的时候,默认不是选的我打开的那个sheet页. 

比如说我在浏览sheet2,  我想用A.xlsx的sheet2 对比 B.xlsx的sheet2. 

结果对比的是 A.xlsx的sheet1和B.xlsx的sheet1的内容.

**Comment by obiscr** [comment]
是的，您说的对，目前对比仅支持第一个sheet。对比其他sheet的feature 已经在计划中了。完成之后会上线。

**Comment by 834116404** [comment]
> 是的，您说的对，目前对比仅支持第一个sheet。对比其他sheet的feature 已经在计划中了。完成之后会上线。

预计什么时候上线啊??

**Comment by obiscr** [comment]
暂时无法提供准确的时间，预估明年年初。

**Comment by obiscr** [comment]
您好，请更新到最新版本 [2024.1.26-222.233](https://exceleditor.obiscr.com/docs/what-new/ExcelEditor-2024.1.26)，在新版本，已经支持选择sheet进行对比。
